# Generated by Django 5.1.1 on 2024-09-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qyery_text', models.CharField(max_length=200)),
                ('query_date', models.DateField(verbose_name='date')),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
