# Generated by Django 5.1.1 on 2024-09-11 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0002_query_delete_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='query_date',
        ),
    ]
